language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit

notifications:
  email:
    - schramm42@me.com

#branches:
#  only:
#    - master