<?php
/**
 * Created by PhpStorm.
 * User: thomasschramm
 * Date: 30.01.14
 * Time: 19:23
 */

namespace Vernum\Tests;

use Vernum\Version;

/**
 * Class VersionTest
 */
class VersionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Version
     */
    private $version;

    /**
     *
     */
    public function testSetPatch()
    {
        $this->version->setPatch("108");
        $this->assertEquals(108, $this->version->getPatch());
    }

    /**
     *
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->version = new Version();
    }


    /**
     *
     */
    public function testSetMajor()
    {
        $this->version->setMajor("23");
        $this->assertEquals(23, $this->version->getMajor());
    }

    /**
     *
     */
    public function testSetMinor()
    {
        $this->version->setMinor("42");
        $this->assertEquals(42, $this->version->getMinor());
    }
}
