<?php
/**
 *
 */

namespace Vernum\Tests;

use Vernum\Version;

/**
 * Class VersionTest
 */
class VersionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Version
     */
    private $version;

    /**
     *
     */
    public function testConstructor()
    {
        $this->version = new Version(2, 10, 213);

        $this->assertEquals(2, $this->version->getMajor());
        $this->assertEquals(10, $this->version->getMinor());
        $this->assertEquals(213, $this->version->getPatch());
    }

    /**
     *
     */
    public function testDump()
    {
        $version = new Version(5, 0, 1, array('dev'));
        $this->assertEquals("5.0.1-dev", $version->dump());

        $version = new Version();
        $this->assertEquals("0.0.0", $version->dump());
    }

    /**
     *
     */
    public function testIsGreaterThan()
    {
        $version1 = new Version(3, 2, 0);
        $version2 = new Version(1, 1, 1);
        $version3 = new Version(1, 4, 1);
        $version4 = new Version(1, 4, 10);
        $version5 = new Version(1, 4, 10);

        $this->assertTrue($version1->isGreaterThan($version2));
        $this->assertTrue($version3->isGreaterThan($version2));
        $this->assertTrue($version4->isGreaterThan($version3));
        $this->assertFalse($version4->isGreaterThan($version5));
        $this->assertFalse($version2->isGreaterThan($version5));
        $this->assertFalse($version2->isGreaterThan($version1));
        $this->assertFalse($version3->isGreaterThan($version4));
    }

    public function testIsEqual()
    {
        $version1 = new Version(3, 2, 0, array('dev'));
        $version2 = new Version(1, 1, 1);
        $version3 = new Version(3, 2, 0);
        $version4 = new Version(3, 2, 0, array('dev'));

        $this->assertFalse($version1->isEqual($version2));
        $this->assertFalse($version1->isEqual($version3));
        $this->assertTrue($version1->isEqual($version4));
    }

    /**
     *
     */
    public function testSetMajor()
    {
        $this->version->setMajor("23");
        $this->assertEquals(23, $this->version->getMajor());
    }

    /**
     *
     */
    public function testSetMinor()
    {
        $this->version->setMinor("42");
        $this->assertEquals(42, $this->version->getMinor());
    }

    /**
     *
     */
    public function testSetPatch()
    {
        $this->version->setPatch("108");
        $this->assertEquals(108, $this->version->getPatch());
    }

    /**
     *
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->version = new Version();
    }
}
